In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type

import numpy as np

# Create NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the data type of the array
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


In [2]:
# 2) Given a NumPy array 'arr', check if its data type is float64.

arr=np.array([1.5,2.6,3.7])
if arr.dtype== 'float64':
    print(f'{arr} the data type is  float64.')
else:
    print(f'{arr} is not a  float64 datatype')

[1.5 2.6 3.7] the data type is  float64.


In [3]:
# 3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

import numpy as np

# Create a NumPy array with data type complex128 containing three complex numbers
arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print("Array:", arr_complex)
print("Data type:", arr_complex.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [4]:
# 4) Convert an existing NumPy array 'arr' of integers to float32 data type

import numpy as np

# Create an existing NumPy array of integers
arr_int = np.array([0, 1, 2, 3, 4, 5])

# Convert the integer array to float32 data type
arr_float32 = arr_int.astype(np.float32)

# Print the original array, converted array, and the new data type
print("Original array:", arr_int)
print("Converted array:", arr_float32)
print("New data type:", arr_float32.dtype)

Original array: [0 1 2 3 4 5]
Converted array: [0. 1. 2. 3. 4. 5.]
New data type: float32


In [5]:
# 5) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

import numpy as np

# Sample float64 array
arr = np.array([1.23456789, 2.34567890, 3.45678901], dtype=np.float64)

# Convert to float32
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1.2345679 2.3456788 3.456789 ]
float32


In [6]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

import numpy as np
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

array_attributes(np.array([1,2,3,6,7]))

((5,), 5, dtype('int64'))

In [7]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np
def array_dimension(arr):
    return arr.ndim
n=np.array([[2,3,4],[34,56,77]])
array_dimension(n)

2

In [8]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

import numpy as np
def item_size_info(n):
    return n.itemsize,n.nbytes

item_size_info(np.array([1.2,2.56,34.3,6.4,7.45]))

(8, 40)

In [9]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array, 

import numpy as np
def array_strides(arr):
    return arr.strides

# Example usage
array = np.arange(12).reshape(3, 4)
print(array_strides(array))  # Output: (16, 4)

(32, 8)


In [10]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage
array = np.arange(12).reshape(3, 4)
shape, strides = shape_stride_relationship(array)
print("Shape:", shape)
print("Strides:", strides)

Shape: (3, 4)
Strides: (32, 8)


In [11]:
#11 . Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

import numpy as np
def create_zeros_array(n):
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print(zeros_array) 

[0. 0. 0. 0. 0.]


In [12]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(row, column):
    return np.ones((row,column))

row=5
column=4
create_ones_matrix(row,column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#13 .Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

start=1
stop=17
step=3
generate_range_array(start,stop,step)

array([ 1,  4,  7, 10, 13, 16])

In [14]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
 # arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
    
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 5.0
num = 10
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`

def create_identity_matrix(n):
    return np.eye(n)

n=3
create_identity_matrix(n)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#16. Write a function that takes a Python list and converts it into a NumPy array

import numpy as np
def list_to_numpy_array(python_list):
    return np.array(python_list)

my_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(my_list)
print(numpy_array)

[1 2 3 4 5]


In [17]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

import numpy as np
def create_numpy_view():

    original_array = np.array([1, 2, 3, 4, 5])
    view_array = original_array.view()

    print("Original array:", original_array)
    print("View array:", view_array)
 
    # Modify the view array
    view_array[0] = 10

    print("Modified view array:", view_array)
    print("Original array after modifying view:", original_array)

create_numpy_view()

Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified view array: [10  2  3  4  5]
Original array after modifying view: [10  2  3  4  5]


In [18]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along the first axis (rows)
concatenated_array1 = concatenate_arrays(array1, array2)
print(concatenated_array1)

# Concatenate along the second axis (columns)
concatenated_array2 = concatenate_arrays(array1, array2, axis=1)
print(concatenated_array2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [19]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

import numpy as np
def concatenate_arrays_horizontally():
    array1 = np.array([[1, 2, 3],[7, 8, 9]])
    array2 = np.array([[4, 5, 6], [7, 8, 9]])

    concatenated_array = np.concatenate((array1, array2), axis=1)
    print(concatenated_array)

concatenate_arrays_horizontally()

[[1 2 3 4 5 6]
 [7 8 9 7 8 9]]


In [20]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list

import numpy as np
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

import numpy as np
def create_integer_array(start, stop, step):
    return np.arange(start, stop + 1, step)


array = create_integer_array(2, 10, 2)
print(array)  # Output: [2 4 6 8 10]

[ 2  4  6  8 10]


In [22]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np
def generate_equally_spaced_array():
    return np.linspace(0, 1, 10)

array = generate_equally_spaced_array()
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np
def generate_logarithmic_spaced_array(start, stop, num):
    return np.logspace(np.log10(start), np.log10(stop), num)

array = generate_logarithmic_spaced_array(1, 1000, 5)
print(array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

def create_dataframe_from_numpy_array():
    data = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(data, columns=["Column1", "Column2", "Column3"])
    return df

df = create_dataframe_from_numpy_array()
print(df)

   Column1  Column2  Column3
0       26       41       87
1       58       53       40
2       36       16       75
3       12       37       41
4       39       63       60


In [25]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import pandas as pd
import numpy as np

def replace_negative_values(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'Column1': [3, -2, 5, 0, -1],
        'Column2': [2, 4, 3, 1, 6]}
df = pd.DataFrame(data)

df = replace_negative_values(df, 'Column1')
print(df)

   Column1  Column2
0        3        2
1        0        4
2        5        3
3        0        1
4        0        6


In [26]:
#26.Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50]) .

import numpy as np
arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]
print(third_element)

30


In [27]:
#27 . Retrieve the element at index (1, 2) from the 2D NumPy array. arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]  
print(element)

6


In [28]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
elements_greater_than_5 = arr[mask]

print(elements_greater_than_5)  

[ 8 10  7]


In [29]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print(sliced_array)

[3 4 5 6]


In [30]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.arr_2d = np.array([[1, 2, 3],
  #                 [4, 5, 6],
  #                 [7, 8, 9]])

import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[1:3, 1:3]
print(sub_array) 

[[5 6]
 [8 9]]


In [31]:
#31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

import numpy as np

def extract_elements_by_indices(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
indices = np.array([[0, 1], [2, 0]])
result = extract_elements_by_indices(arr, indices)
print(result)

[2 7]


In [32]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np
def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
result = filter_elements(arr, threshold)
print(result) 

[ 8 10  7]


In [33]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

import numpy as np
def extract_elements_3d(arr, indices_x, indices_y, indices_z):
    return arr[indices_x, indices_y, indices_z]

arr = np.arange(24).reshape(2, 3, 4)
indices_x = np.array([0, 1])
indices_y = np.array([1, 0])
indices_z = np.array([2, 3])
result = extract_elements_3d(arr, indices_x, indices_y, indices_z)
print(result) 

[ 6 15]


In [34]:
#34 . Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np
def filter_by_conditions(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]

arr = np.array([2, 5, 8, 3, 7, 4])
condition1 = arr > 3
condition2 = arr < 8
result = filter_by_conditions(arr, condition1, condition2)
print(result)  

[5 7 4]


In [35]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np
def extract_elements_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
result = extract_elements_by_indices(arr, row_indices, col_indices)
print(result)  

[2 9]


In [36]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np
def add_scalar(arr, scalar):
    return arr + scalar

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
scalar = 5
result = add_scalar(arr, scalar)
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37 .Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

import numpy as np
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1.T * arr2
print("Result of multiplying each row of arr2 by the corresponding element in arr1:\n", result)

Result of multiplying each row of arr2 by the corresponding element in arr1:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [38]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

# Define the arrays
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])

# Add arr1 to each row of arr2 using broadcasting
result = arr1 + arr2.T
print("Result of adding arr1 to each row of arr2:\n", result.T)

Result of adding arr1 to each row of arr2:
 [[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [39]:
#39.  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np
def add_arrays(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = add_arrays(arr1, arr2)
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

import numpy as np
def multiply_arrays(arr1, arr2):
    return np.einsum('ij,ik->ijk', arr1, arr2)

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])
result = multiply_arrays(arr1, arr2)
print(result)

[[[ 7  8]
  [14 16]
  [21 24]]

 [[36 40]
  [45 50]
  [54 60]]]


In [41]:
#41. Calculate column wise mean for the given array. arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Calculate column-wise mean
column_mean = arr.mean(axis=0)
print("Column-wise mean:", column_mean)

Column-wise mean: [2.5 3.5 4.5]


In [42]:
#42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find maximum value in each row
row_max = arr.max(axis=1)
print("Maximum value in each row:", row_max)

Maximum value in each row: [3 6]


In [43]:
#43. For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find indices of maximum value in each column
indices_max_col = arr.argmax(axis=0)
print("Indices of maximum value in each column:", indices_max_col)

Indices of maximum value in each column: [1 1 1]


In [44]:
#44. For the given array, apply custom function to calculate moving sum along rows. arr = np.array([[1, 2, 3], [4, 5, 6]])

# Custom function to calculate moving sum along rows
def moving_sum(arr, window_size):
    return np.array([np.convolve(row, np.ones(window_size, dtype=int), 'valid') for row in arr])

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Apply custom function
moving_sum_result = moving_sum(arr, 2)
print("Moving sum along rows:", moving_sum_result)

Moving sum along rows: [[ 3  5]
 [ 9 11]]


In [45]:
#45. In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]])

# Given array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
all_even = np.all(arr % 2 == 0, axis=0)
print("All elements in each column are even:", all_even)

All elements in each column are even: [False False False]


In [46]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

# Given array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape array to 2 rows and 3 columns
reshaped_matrix = reshape_array(original_array, 2, 3)
print("Reshaped matrix:\n", reshaped_matrix)

Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [47]:
#47. Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

# Given matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)
print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [48]:
#48,  Write a function that concatenates two given arrays along a specified axis.  array1 = np.array([[1, 2], [3, 4]]) ,array2 = np.array([[5, 6], [7, 8]])

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along axis 1 (columns)
concatenated_array_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [49]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis. original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, indices_or_sections, axis):
    return np.split(arr, indices_or_sections, axis=axis)

# Given array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split along axis 0 (rows)
split_arrays_0 = split_array(original_array, 3, axis=0)
print("Split along axis 0:", split_arrays_0)

# Split along axis 1 (columns)
split_arrays_1 = split_array(original_array, 3, axis=1)
print("Split along axis 1:", split_arrays_1)

Split along axis 0: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split along axis 1: [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [50]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]

def insert_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

# Given array and indices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Insert and delete elements
modified_array = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", modified_array)

Modified array: [ 1 10  4 11  5]


In [51]:
#51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

# Create arrays
arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 11)

# Element-wise addition
sum_array = arr1 + arr2
print("Element-wise addition:", sum_array)

Element-wise addition: [11  9  7  7 15 16 16  9 16 14]


In [52]:
#52.  Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

# Create arrays
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

# Element-wise subtraction
diff_array = arr1 - arr2
print("Element-wise subtraction:", diff_array)

Element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

# Create arrays
arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 6)

# Element-wise multiplication
product_array = arr1[:5] * arr2
print("Element-wise multiplication:", product_array)

Element-wise multiplication: [ 1 14  9  4 25]


In [54]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`

# Create arrays
arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)

# Element-wise division
division_array = arr1 / arr2
print("Element-wise division:", division_array)

Element-wise division: [2. 2. 2. 2. 2.]


In [55]:
#55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise

# Create arrays
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

# Element-wise exponentiation
exp_array = np.power(arr1, arr2)
print("Element-wise exponentiation:", exp_array)

Element-wise exponentiation: [ 1 16 27 16  5]


In [56]:
#56.. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring):
    return np.char.count(arr, substring).sum()

# Given array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Count occurrences of 'hello'
count_hello = count_substring(arr, 'hello')
print("Occurrences of 'hello':", count_hello)

Occurrences of 'hello': 3


In [57]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

# Given array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
uppercase_chars = extract_uppercase(arr)
print("Uppercase characters:", uppercase_chars)

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [58]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace 'apple' with 'orange'
new_arr = replace_substring(arr, 'apple', 'orange')
print("Replaced array:", new_arr)

Replaced array: ['orange' 'banana' 'grape' 'pineorange']


In [59]:
#59. . Write a function that concatenates strings in a NumPy array element-wise.
#arr1 = np.array(['Hello', 'World'])
#arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# Given arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate element-wise
concatenated_arr = concatenate_strings(arr1, arr2)
print("Concatenated array:", concatenated_arr)

Concatenated array: ['HelloOpen' 'WorldAI']


In [60]:
#60. Write a function that finds the length of the longest string in a NumPy array.
#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    return max(np.char.str_len(arr))

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [61]:
#61. . Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Mean: 500.75
Median: 457.5
Variance: 89252.6475
Standard Deviation: 298.7518158940628


In [62]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

# Generate an array of 50 random numbers between 1 and 100
data = np.random.uniform(1, 100, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

25th Percentile: 33.26220412003425
75th Percentile: 81.19748861353891


In [63]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

# Create two arrays representing two sets of variables
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

# Compute the correlation coefficient
correlation_matrix = np.corrcoef(arr1, arr2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)

Correlation Coefficient Matrix:
 [[ 1.        -0.0696963]
 [-0.0696963  1.       ]]


In [64]:
#64. Create two matrices and perform matrix multiplication using NumPy's dot function.

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
matrix_product = np.dot(matrix1, matrix2)
print("Matrix product:\n", matrix_product)

Matrix product:
 [[19 22]
 [43 50]]


In [65]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

# Create an array of 50 integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)

# Calculate the first and third quartiles
first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)

print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile:", first_quartile)
print("Third Quartile:", third_quartile)

10th Percentile: 89.7
50th Percentile (Median): 414.5
90th Percentile: 931.5
First Quartile: 217.25
Third Quartile: 706.5


In [66]:
#66. Create a NumPy array of integers and find the index of a specific element.

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element
element = 30
index = np.where(arr == element)[0][0]
print("Index of element", element, ":", index)

Index of element 30 : 2


In [67]:
#67. Generate a random NumPy array and sort it in ascending order.

# Generate a random NumPy array
arr = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

Sorted array: [18 31 33 56 61 66 67 71 77 90]


In [68]:
#68. Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements >20
filtered_arr = arr[arr > 20]
print("Filtered array:", filtered_arr)

Filtered array: [25 42 30]


In [69]:
#69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15])

# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]
print("Filtered array:", filtered_arr)

Filtered array: [12 15]


In [70]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Filtered array:", filtered_arr)

Filtered array: [20 30 40]


In [71]:
#71. For the given NumPy array, check its byte order using the dtype attribute byteorder. arr = np.array([1, 2, 3])

# Given array
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


In [72]:
#72. For the given NumPy array, perform byte swapping in place using byteswap().

arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)
print("Byte-swapped array:", arr)

Byte-swapped array: [16777216 33554432 50331648]


In [73]:
#73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder(). 
#arr = np.array([1, 2, 3], dtype=np.int32)

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)

Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [74]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder().
#arr = np.array([1, 2, 3], dtype=np.int32)

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order conditionally based on system endianness
swapped_arr = arr.newbyteorder('S')
print("Byte-swapped array based on system endianness:", swapped_arr)

Byte-swapped array based on system endianness: [16777216 33554432 50331648]


In [75]:
#For the given NumPy array, check if byte swapping is necessary for the current system using dtype arr = np.array([1, 2, 3], dtype=np.int32)   

# Given array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
is_swapping_needed = arr.dtype.byteorder == '>'
print("Is byte swapping necessary:", is_swapping_needed)

Is byte swapping necessary: False


In [76]:
#76.Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

# Create array
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [77]:
#77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

# Create a 2D array
matrix = np.random.randint(1, 10, (3, 3))

# Extract a slice
view_slice = matrix[:2, :2]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Observe changes in the original matrix
print("Original matrix after modification:\n", matrix)

Original matrix after modification:
 [[100   3   3]
 [  2   6   8]
 [  3   5   3]]


In [78]:
#78.  Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

# Create a 2D array
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice
view_b = array_a[:, :2]

# Broadcast addition of 5 to view_b
view_b += 5

# Check if it alters the original array
print("Original array after modification:\n", array_a)

Original array after modification:
 [[ 6  7  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]


In [79]:
#79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it
#    reflects changes in the original orig_array.

# Create a 2D array
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Check if it reflects changes in the original array
print("Original array after modification:\n", orig_array)

Original array after modification:
 [[100   2   3   4]
 [  5   6   7   8]]


In [80]:
#80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

# Create a 2D array
data = np.random.randint(1, 10, (3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 100

# Verify if it affects the original data
print("Original array:\n", data)
print("Modified copy of elements greater than 5:", data_copy)

Original array:
 [[7 5 4 4]
 [5 8 6 3]
 [3 5 8 4]]
Modified copy of elements greater than 5: [100   8   6   8]


In [81]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

# Create two matrices A and B
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition result:\n", addition_result)
print("Subtraction result:\n", subtraction_result)

Matrix A:
 [[4 1 2]
 [8 5 6]
 [5 1 1]]
Matrix B:
 [[5 5 9]
 [2 6 3]
 [6 6 5]]
Addition result:
 [[ 9  6 11]
 [10 11  9]
 [11  7  6]]
Subtraction result:
 [[-1 -4 -7]
 [ 6 -1  3]
 [-1 -5 -4]]


In [82]:
#82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

# Generate two matrices C and D
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

# Perform matrix multiplication
matrix_multiplication_result = np.dot(C, D)
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication result:\n", matrix_multiplication_result)

Matrix C:
 [[8 7]
 [4 5]
 [8 8]]
Matrix D:
 [[4 1 2 8]
 [2 5 2 1]]
Matrix multiplication result:
 [[46 43 30 71]
 [26 29 18 37]
 [48 48 32 72]]


In [83]:
#83. Create a matrix E and find its transpose.

# Create a matrix E
E = np.random.randint(1, 10, (3, 3))

# Find the transpose
transpose_E = np.transpose(E)
print("Matrix E:\n", E)
print("Transpose of E:\n", transpose_E)

Matrix E:
 [[4 9 8]
 [4 7 6]
 [3 4 1]]
Transpose of E:
 [[4 4 3]
 [9 7 4]
 [8 6 1]]


In [84]:
#84. Generate a square matrix F and compute its determinant.

# Generate a square matrix F
F = np.random.randint(1, 10, (3, 3))

# Compute the determinant
determinant_F = np.linalg.det(F)
print("Matrix F:\n", F)
print("Determinant of F:", determinant_F)

Matrix F:
 [[2 5 9]
 [4 9 6]
 [4 2 4]]
Determinant of F: -163.99999999999991


In [85]:
#85. Create a square matrix G and find its inverse.  

# Create a square matrix G
G = np.random.randint(1, 10, (3, 3))

# Find the inverse
inverse_G = np.linalg.inv(G)
print("Matrix G:\n", G)
print("Inverse of G:\n", inverse_G)

Matrix G:
 [[8 8 4]
 [7 4 6]
 [5 2 7]]
Inverse of G:
 [[-0.33333333  1.         -0.66666667]
 [ 0.39583333 -0.75        0.41666667]
 [ 0.125      -0.5         0.5       ]]
